<?php
/**
 * Template for the settings page.
 *
 * @package AI_Story_Maker
 * @since   0.1.0
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Exit if accessed directly.
}

?>
<div class="wrap">
<?php
	// Add a nonce for AJAX security
	$ajax_nonce = wp_create_nonce( 'aistma_save_setting' );
	?>
	<script type="text/javascript">
		window.aistmaSettings = {
			ajaxUrl: '<?php echo esc_url( admin_url( 'admin-ajax.php' ) ); ?>',
			nonce: '<?php echo esc_js( $ajax_nonce ); ?>'
		};
	</script>

<div id="aistma-settings-message"></div>

<h2><?php esc_html_e( 'General Settings', 'ai-story-maker' ); ?></h2>
<p><?php esc_html_e( 'Configure the general settings for AI Story Maker. These settings control how the plugin behaves and generates content.', 'ai-story-maker' ); ?></p>

<div class="aistma-settings-grid">
	<div class="aistma-setting-item">
		<b><label for="aistma_clear_log_cron"><?php esc_html_e( 'Log Retention (Days):', 'ai-story-maker' ); ?></label></b>
		<p>
			<?php
			printf(
			/* translators: %s: link to log page */
				wp_kses_post( __( 'AI Story Maker maintains a detailed log of its activities. Choose how many days to retain the logs, or set to 0 to keep them indefinitely. You can view the log <a href="%s">here</a>.', 'ai-story-maker' ) ),
				esc_url( admin_url( 'admin.php?page=aistma-settings&tab=log' ) )
			);
			?>
		</p>
		<select id="aistma_clear_log_cron" data-setting="aistma_clear_log_cron">
			<?php for ( $i = 0; $i <= 30; $i++ ) : ?>
				<option value="<?php echo esc_attr( $i ); ?>" <?php selected( get_option( 'aistma_clear_log_cron' ), $i ); ?>>
					<?php echo esc_attr( $i ); ?> <?php esc_html_e( 'Day(s)', 'ai-story-maker' ); ?>
				</option>
			<?php endfor; ?>
		</select>
	</div>
	
	<div class="aistma-setting-item">
		<b><label for="aistma_generate_story_cron"><?php esc_html_e( 'Generate New Stories Every (Days):', 'ai-story-maker' ); ?></label></b>
		<p>
			<?php esc_html_e( 'AI Story Maker can automatically generate new stories at regular intervals. Set to 0 to disable scheduled generation.', 'ai-story-maker' ); ?>
		</p>
		<select id="aistma_generate_story_cron" data-setting="aistma_generate_story_cron">
			<?php for ( $i = 0; $i <= 30; $i++ ) : ?>
				<option value="<?php echo esc_attr( $i ); ?>" <?php selected( get_option( 'aistma_generate_story_cron' ), $i ); ?>>
					<?php echo esc_attr( $i ); ?> <?php esc_html_e( 'Day(s)', 'ai-story-maker' ); ?>
				</option>
			<?php endfor; ?>
		</select>
	</div>
	
	<div class="aistma-setting-item">
		<b><label for="aistma_opt_auther"><?php esc_html_e( 'Select Story Author:', 'ai-story-maker' ); ?></label></b>
		<p>
			<?php esc_html_e( 'Select the author for AI-generated stories. If you need to create a new author, you can do so', 'ai-story-maker' ); ?>
			<a href="<?php echo esc_url( admin_url( 'user-new.php?role=author' ) ); ?>" target="_blank"><?php esc_html_e( 'here', 'ai-story-maker' ); ?></a>.
			<?php esc_html_e( 'Ensure the role is set to "Author".', 'ai-story-maker' ); ?>
		</p>
		<select id="aistma_opt_auther" data-setting="aistma_opt_auther">
			<?php
			$users = get_users( array( 'role__in' => array( 'author', 'administrator' ) ) );
			foreach ( $users as $user ) :
				?>
				<option value="<?php echo esc_attr( $user->ID ); ?>" <?php selected( get_option( 'aistma_opt_auther' ), $user->ID ); ?>>
					<?php echo esc_html( $user->display_name ); ?>
				</option>
			<?php endforeach; ?>
		</select>
	</div>
	
	<div class="aistma-setting-item">
		<p>
			<b><label for="aistma_show_ai_attribution">
				<input type="checkbox" id="aistma_show_ai_attribution" data-setting="aistma_show_ai_attribution" value="1" <?php checked( get_option( 'aistma_show_ai_attribution', 1 ), 1 ); ?> />
				<?php esc_html_e( 'Show "Generated by AI" attribution at the end of each story', 'ai-story-maker' ); ?>
			</label></b>
		</p>
		<p style="margin-top: 10px; font-size: 12px; color: #666;">
			<?php esc_html_e( 'Recommended: Keeping this enabled promotes transparency and trust with your readers.', 'ai-story-maker' ); ?>
			<?php esc_html_e( 'Note: Future regulations may require disclosure of AI-generated content.', 'ai-story-maker' ); ?>
		</p>
	</div>
	
	<div class="aistma-setting-item">
		<p>
			<b><label for="aistma_show_exedotcom_attribution">
				<input type="checkbox" id="aistma_show_exedotcom_attribution" data-setting="aistma_show_exedotcom_attribution" value="1" <?php checked( get_option( 'aistma_show_exedotcom_attribution', 0 ), 1 ); ?> />
				<?php esc_html_e( 'Show "Created by AI Story Maker" attribution', 'ai-story-maker' ); ?>
			</label></b>
		</p>
		<p style="margin-top:10px; font-size: 12px; color: #666;">
			<?php esc_html_e( 'Support our work by showing a small attribution link to Exedotcom.ca. This helps us continue developing and improving AI Story Maker.', 'ai-story-maker' ); ?>
			<?php esc_html_e( 'Your support means a lot to us!', 'ai-story-maker' ); ?>
		</p>
	</div>
</div>

<div class="aistma-generate-stories-section">
	<h3><?php esc_html_e( 'Manual Story Generation', 'ai-story-maker' ); ?></h3>
	<p><?php esc_html_e( 'Click the button below to manually generate new stories using your current prompts and settings.', 'ai-story-maker' ); ?></p>
	<button id="aistma-generate-stories-button" class="button button-primary">
		<?php esc_html_e( 'Generate Stories Now', 'ai-story-maker' ); ?>
	</button>
	<input type="hidden" id="generate-story-nonce" value="<?php echo esc_attr( wp_create_nonce( 'generate_ai_stories' ) ); ?>">
</div>
</div> 