<?php
/**
 * Template for the settings page.
 *
 * @package AI_Story_Maker
 * @since   0.1.0
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Exit if accessed directly.
}
?>
<div class="wrap">
	<div class="aistma-style-settings">

<h2><?php esc_html_e( 'General Settings', 'ai-story-maker' ); ?></h2>
<?php
	// Add a nonce for AJAX security
	$ajax_nonce = wp_create_nonce( 'aistma_save_setting' );

	// Ensure attribution values are set to the correct defaults
	if ( ! get_option( 'aistma_author_name' ) || get_option( 'aistma_author_name' ) === 'Exedotcom.ca' ) {
		update_option( 'aistma_author_name', 'Story Maker Plugin' );
	}
	if ( ! get_option( 'aistma_author_url' ) || get_option( 'aistma_author_url' ) === 'https://exedotcom.ca' ) {
		update_option( 'aistma_author_url', 'https://storymakerplugin.com' );
	}
	?>
	<script type="text/javascript">
		window.aistmaSettings = {
			ajaxUrl: '<?php echo esc_url( admin_url( 'admin-ajax.php' ) ); ?>',
			nonce: '<?php echo esc_js( $ajax_nonce ); ?>'
		};
	</script>

<div id="aistma-settings-message" style="display:none;"></div>

<p><?php esc_html_e( 'Configure the general settings for AI Story Maker. These settings control how the plugin behaves and generates content. For social media publishing settings, visit the Social Media Integration tab.', 'ai-story-maker' ); ?></p>

<div class="aistma-settings-vertical">
	<div class="aistma-setting-item-compact">
		<div class="setting-label">
				<p><b><?php esc_html_e( 'Generate New Stories Every (Days)', 'ai-story-maker' ); ?></b>

		<?php esc_html_e( 'Automatically generate stories at regular intervals. Set to 0 to disable.', 'ai-story-maker' ); ?></p>

			<select id="aistma_generate_story_cron" data-setting="aistma_generate_story_cron">
				<?php for ( $i = 0; $i <= 30; $i++ ) : ?>
					<option value="<?php echo esc_attr( $i ); ?>" <?php selected( get_option( 'aistma_generate_story_cron', 2 ), $i ); ?>>
						<?php echo esc_attr( $i ); ?> <?php esc_html_e( 'Day(s)', 'ai-story-maker' ); ?>
					</option>
				<?php endfor; ?>
			</select>
		</div>
<hr>
		<div class="setting-label">
		<p>
			<b><?php esc_html_e( 'Story Author', 'ai-story-maker' ); ?></b>
	
				<?php esc_html_e( 'Select author for AI-generated stories.', 'ai-story-maker' ); ?>
				<a href="<?php echo esc_url( admin_url( 'user-new.php?role=author' ) ); ?>" target="_blank"><?php esc_html_e( 'Create new author', 'ai-story-maker' ); ?></a>.
			</p>

			<select id="aistma_opt_auther" data-setting="aistma_opt_auther">
				<?php
				$users = get_users( array( 'role__in' => array( 'author', 'administrator' ) ) );
				foreach ( $users as $user ) :
					?>
					<option value="<?php echo esc_attr( $user->ID ); ?>" <?php selected( get_option( 'aistma_opt_auther' ), $user->ID ); ?>>
						<?php echo esc_html( $user->display_name ); ?>
					</option>
				<?php endforeach; ?>
			</select>
		</div>
<hr>
		<label for="aistma_show_ai_attribution">
			<input type="checkbox" id="aistma_show_ai_attribution" data-setting="aistma_show_ai_attribution" value="1" <?php checked( get_option( 'aistma_show_ai_attribution', 1 ), 1 ); ?> />

				<strong><?php esc_html_e( 'Show "Generated by AI" attribution at the end of each story', 'ai-story-maker' ); ?></strong>
				
					<?php esc_html_e( 'Recommended: Promotes transparency and trust with readers. Future regulations may require AI content disclosure.', 'ai-story-maker' ); ?>
	

		</label>
<hr>
		<label for="aistma_show_exedotcom_attribution">
			<input type="checkbox" id="aistma_show_exedotcom_attribution" data-setting="aistma_show_exedotcom_attribution" value="1" <?php checked( get_option( 'aistma_show_exedotcom_attribution', 0 ), 1 ); ?> />

				<strong><?php esc_html_e( 'Show "Created by AI Story Maker" attribution', 'ai-story-maker' ); ?></strong>
				<div class="checkbox-description">
					<?php esc_html_e( 'Show an attribution link to your company/website. Helps users know who maintains the plugin.', 'ai-story-maker' ); ?>

			</div>
		</label>
		<input type="hidden" id="aistma_author_name" value="<?php echo esc_attr( get_option( 'aistma_author_name', 'Story Maker Plugin' ) ); ?>" />
		<input type="hidden" id="aistma_author_url" value="<?php echo esc_attr( get_option( 'aistma_author_url', 'https://storymakerplugin.com' ) ); ?>" />
<hr>
		<div class="setting-label">
			<h4><?php esc_html_e( 'Log Retention (Days)', 'ai-story-maker' ); ?></h4>
			<p>
				<?php
				printf(
				/* translators: %s: link to log page */
					wp_kses_post( __( 'Choose how many days to retain logs, or 0 for indefinitely. <a href="%s">View logs</a>.', 'ai-story-maker' ) ),
					esc_url( admin_url( 'admin.php?page=aistma-settings&tab=log' ) )
				);
				?>
			</p>
<hr>
			<select id="aistma_clear_log_cron" data-setting="aistma_clear_log_cron">
				<?php for ( $i = 0; $i <= 30; $i++ ) : ?>
					<option value="<?php echo esc_attr( $i ); ?>" <?php selected( get_option( 'aistma_clear_log_cron' ), $i ); ?>>
						<?php echo esc_attr( $i ); ?> <?php esc_html_e( 'Day(s)', 'ai-story-maker' ); ?>
					</option>
				<?php endfor; ?>
			</select>
		</div>
	</div>

	<div style="margin-top: 20px;">
		<button id="aistma-save-settings-btn" class="button button-primary" disabled>
			<?php esc_html_e( 'Save Settings', 'ai-story-maker' ); ?>
		</button>
	</div>
	<?php // Generation controls moved to a reusable template included globally. ?>
</div>
<script>
(function () {
	var btn     = document.getElementById('aistma-save-settings-btn');
	var msgEl   = document.getElementById('aistma-settings-message');
	var nonce   = window.aistmaSettings ? window.aistmaSettings.nonce   : '';
	var ajaxUrl = window.aistmaSettings ? window.aistmaSettings.ajaxUrl : '';

	function showMsg(msg, ok) {
		if (!msgEl) return;
		msgEl.textContent = msg;
		msgEl.style.cssText = 'display:block;padding:8px 12px;margin:10px 0;border-radius:4px;'
			+ (ok ? 'color:#28a745;background:#d4edda;border:1px solid #c3e6cb;'
			      : 'color:#dc3545;background:#f8d7da;border:1px solid #f5c6cb;');
		setTimeout(function () { msgEl.style.display = 'none'; }, 4000);
	}

	function fieldVal(el) {
		return el.type === 'checkbox' ? (el.checked ? '1' : '0') : el.value;
	}

	// Enable Save button when any field changes
	document.querySelectorAll('[data-setting]').forEach(function (el) {
		el.addEventListener('change', function () { btn.disabled = false; });
		el.addEventListener('input',  function () { btn.disabled = false; });
	});

	btn.addEventListener('click', function () {
		var fields = document.querySelectorAll('[data-setting]');
		btn.disabled = true;
		btn.textContent = '<?php echo esc_js( __( 'Saving…', 'ai-story-maker' ) ); ?>';
		var done = 0, errors = 0;
		fields.forEach(function (field) {
			var fd = new FormData();
			fd.append('action',          'aistma_save_setting');
			fd.append('aistma_security', nonce);
			fd.append('setting_name',    field.getAttribute('data-setting'));
			fd.append('setting_value',   fieldVal(field));
			fetch(ajaxUrl, { method: 'POST', body: fd })
				.then(function (r) { return r.text(); })
				.then(function (t) { try { if (!JSON.parse(t).success) errors++; } catch(e) { errors++; } })
				.catch(function () { errors++; })
				.finally(function () {
					done++;
					if (done < fields.length) return;
					btn.textContent = '<?php echo esc_js( __( 'Save Settings', 'ai-story-maker' ) ); ?>';
					if (errors) {
						showMsg('<?php echo esc_js( __( 'Some settings could not be saved.', 'ai-story-maker' ) ); ?>', false);
						btn.disabled = false;
					} else {
						showMsg('<?php echo esc_js( __( 'Settings saved!', 'ai-story-maker' ) ); ?>', true);
						btn.disabled = true;
					}
				});
		});
	});
}());
</script>

</div>

<?php
// Include weekly management template for admins
if ( current_user_can( 'manage_options' ) ) {
	include AISTMA_PATH . 'admin/templates/weekly-management-template.php';
}
?>
</div>