name: Rebuild Plugin Zip

on:
  push:
    branches:
      - main

jobs:
  rebuild-zip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Delete old ai-story-maker.zip (if exists)
        run: |
          if [ -f ai-story-maker.zip ]; then
            rm ai-story-maker.zip
          fi

      - name: Create new ai-story-maker.zip
        run: |
          cd ai-story-maker
          zip -r ../ai-story-maker.zip ./
      
      - name: Upload the new zip (optional - if you want artifacts)
        uses: actions/upload-artifact@v4
        with:
          name: ai-story-maker-zip
          path: ai-story-maker.zip
