name: Release AI Story Maker Plugin

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Zip ai-story-maker folder
        run: |
          cd ai-story-maker
          zip -r ../ai-story-maker.zip ./

      - name: Create Release and Upload Plugin Zip
        uses: softprops/action-gh-release@v2
        with:
          files: ai-story-maker.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
